events {}

http {
  server {
    listen 8443 ssl;
    server_name agent-demo.example.com;

    ssl_certificate     /etc/cds-agent/certs/agent-demo.example.com/fullchain.pem;
    ssl_certificate_key /etc/cds-agent/certs/agent-demo.example.com/privkey.pem;

    location / {
      return 200 "ok\n";
    }
  }
}
